# Generated by Django 3.2.4 on 2021-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alllogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllogin',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
